export const CATEGORIA_OPTIONS = [
    { value: "suscripcion", label: "📺 Suscripción" },
    { value: "prestamo", label: "🏦 Préstamo" },
    { value: "tarjeta", label: "💳 Tarjeta" },
    { value: "servicio", label: "⚡ Servicio" },
    { value: "alquiler", label: "🏠 Alquiler" },
    { value: "salud", label: "🏥 Salud" },
    { value: "mascotas", label: "🐾 Mascotas" },
    { value: "educacion", label: "📚 Educación" },
    { value: "otro", label: "📋 Otro" },
];

export const FRECUENCIA_OPTIONS = [
    { value: "semanal", label: "Semanal" },
    { value: "quincenal", label: "Quincenal" },
    { value: "mensual", label: "Mensual" },
    { value: "bimestral", label: "Bimestral" },
    { value: "trimestral", label: "Trimestral" },
    { value: "semestral", label: "Semestral" },
    { value: "anual", label: "Anual" },
];

export const DIAS_OPTIONS = [
    { value: "", label: "Sin recordatorio" },
    { value: "1", label: "1 día antes" },
    { value: "2", label: "2 días antes" },
    { value: "3", label: "3 días antes" },
    { value: "5", label: "5 días antes" },
    { value: "7", label: "1 semana antes" },
];

export const SUGERENCIAS: { nombre: string; icono: string; categoria: string }[] = [
    { nombre: "Netflix", icono: "🎬", categoria: "suscripcion" },
    { nombre: "Spotify", icono: "🎵", categoria: "suscripcion" },
    { nombre: "Disney+", icono: "🏰", categoria: "suscripcion" },
    { nombre: "HBO Max", icono: "📺", categoria: "suscripcion" },
    { nombre: "Amazon Prime", icono: "📦", categoria: "suscripcion" },
    { nombre: "YouTube Premium", icono: "▶️", categoria: "suscripcion" },
    { nombre: "Apple Music", icono: "🍎", categoria: "suscripcion" },
    { nombre: "iCloud", icono: "☁️", categoria: "suscripcion" },
    { nombre: "ChatGPT", icono: "🤖", categoria: "suscripcion" },
    { nombre: "Gimnasio", icono: "💪", categoria: "suscripcion" },
    { nombre: "Gollo", icono: "🏪", categoria: "prestamo" },
    { nombre: "Mexpress", icono: "🛒", categoria: "prestamo" },
    { nombre: "Importadora", icono: "🏬", categoria: "prestamo" },
    { nombre: "Banco Nacional", icono: "🏦", categoria: "prestamo" },
    { nombre: "BAC", icono: "💳", categoria: "tarjeta" },
    { nombre: "BCR", icono: "💳", categoria: "tarjeta" },
    { nombre: "Scotiabank", icono: "💳", categoria: "tarjeta" },
    { nombre: "Tarjeta Credito", icono: "💳", categoria: "tarjeta" },
    { nombre: "CCSS", icono: "🏥", categoria: "servicio" },
    { nombre: "INS", icono: "🛡️", categoria: "servicio" },
    { nombre: "Agua", icono: "💧", categoria: "servicio" },
    { nombre: "Luz", icono: "⚡", categoria: "servicio" },
    { nombre: "Internet", icono: "🌐", categoria: "servicio" },
    { nombre: "Teléfono", icono: "📱", categoria: "servicio" },
    { nombre: "Alquiler", icono: "🏠", categoria: "alquiler" },
    { nombre: "Condominio", icono: "🏢", categoria: "alquiler" },
    { nombre: "Medicamentos", icono: "💊", categoria: "salud" },
    { nombre: "Seguro médico", icono: "🏥", categoria: "salud" },
    { nombre: "Cita médica", icono: "👨‍⚕️", categoria: "salud" },
    { nombre: "Vitaminas", icono: "💊", categoria: "salud" },
    { nombre: "Farmacia", icono: "💊", categoria: "salud" },
    { nombre: "Concentrado", icono: "🐾", categoria: "mascotas" },
    { nombre: "Veterinario", icono: "🐕", categoria: "mascotas" },
    { nombre: "Vacuna mascota", icono: "💉", categoria: "mascotas" },
    { nombre: "Guardería mascota", icono: "🏠", categoria: "mascotas" },
    { nombre: "Arena gato", icono: "🐱", categoria: "mascotas" },
    { nombre: "Colegio", icono: "📚", categoria: "educacion" },
    { nombre: "Universidad", icono: "🎓", categoria: "educacion" },
    { nombre: "Curso online", icono: "💻", categoria: "educacion" },
    { nombre: "Inglés", icono: "🗣️", categoria: "educacion" },
    { nombre: "Transporte escolar", icono: "🚌", categoria: "educacion" },
    { nombre: "Seguro", icono: "🛡️", categoria: "otro" },
];

export const CATEGORIA_LABELS_SUGERENCIAS: Record<string, string> = {
    suscripcion: "📺 Suscripciones",
    prestamo: "🏦 Préstamos",
    tarjeta: "💳 Tarjetas",
    servicio: "⚡ Servicios",
    alquiler: "🏠 Alquiler",
    salud: "🏥 Salud",
    mascotas: "🐾 Mascotas",
    educacion: "📚 Educación",
    otro: "📋 Otro",
};
